spring:
    application:
        name: springbootZuul

server:
    port: 6005

eureka:
    client:
        service-url:
            defaultZone : http://localhost:5000/eureka/

zuul:
    routes:
        sbService :
            path : /sbService/**
            serviceId : springbootService
#            path : /sbService/**
#            serviceId : springbootService
#
#
#zuul:
#  sensitiveHeaders: "abcd-test"
#  routes:
#    romp:
#      path: /testA/**
#      serviceId: test-cloud-a
#      sensitiveHeaders: "abcd-test"
#多个的时候，就直接配置多个，切记缩进
#    rompSchedule:
#      path: /testB/**
#      serviceId: test-cloud-b
#      sensitiveHeaders: "abcd-test"
